[ubuntu]
smp = 8
mem.size = 8
mem.unit = "G"
bios = "/usr/share/qemu/OVMF.fd"
disk = "ubuntu-x86_64.qcow2"

[ubuntu.mods.install]
kernel = "https://releases.ubuntu.com/24.04/netboot/amd64/linux"
initrd = "https://releases.ubuntu.com/24.04/netboot/amd64/initrd"
append = "cloud-config-url=/dev/null ip=dhcp url=https://releases.ubuntu.com/noble/ubuntu-24.04-latest-live-server-amd64.iso only-ubiquity console=ttyS0,115200"
extras.action.reboot = "shutdown"

[ubuntu.mods.sev]
sev.type = "sev"

[ubuntu.mods.sev-es]
sev.type = "es"
bios = "/usr/share/ovmf/OVMF.amdsev.fd"

[ubuntu.mods.sev-snp]
sev.type = "snp"
bios = "/usr/share/ovmf/OVMF.amdsev.fd"
