[fedora]
smp = 8
mem.size = 8
mem.unit = "G"
bios = "/usr/share/qemu/OVMF.fd"
disk = "fedora-x86_64.qcow2"

[fedora.mods.install]
kernel = "https://download.fedoraproject.org/pub/fedora/linux/releases/43/Server/x86_64/os/images/pxeboot/vmlinuz"
initrd = "https://download.fedoraproject.org/pub/fedora/linux/releases/43/Server/x86_64/os/images/pxeboot/initrd.img"
append = "inst.stage2=https://download.fedoraproject.org/pub/fedora/linux/releases/43/Server/x86_64/os/ ip=dhcp console=ttyS0,115200"
extras.action.reboot = "shutdown"

[fedora.mods.sev]
sev.type = "sev"

[fedora.mods.sev-es]
sev.type = "es"
bios = "/usr/share/ovmf/OVMF.amdsev.fd"

[fedora.mods.sev-snp]
sev.type = "snp"
bios = "/usr/share/ovmf/OVMF.amdsev.fd"
